### ISSUE TITLE
I can't give rights to other users

### ISSUE THREAD

**Issue by enthalpie91** [pluginsGLPI/mreporting#100]
Hi
I would like to give access to the plugins at the "normal" users of glpi
i got to modify profil , and more reports
when i clic to a report and want to change rights to read the action is not registred and return to no right

**Comment by jeromedrouet** [comment]
![missing_more_reporting_in_tools_rights](https://user-images.githubusercontent.com/4835127/58949959-f3af4800-878d-11e9-80bd-86d1d7506299.PNG)

we can not give rights to additiional profiles on this mreporting plugins because there is no "more reporting" item defined when editing profiles rights
GLPI 9.3.4 - more reporting 1.5.3

is there another way to do it ?

**Comment by trasher** [comment]
Please use forums to get support; thank you.
